# Generated by Django 6.0.5 on 2026-06-27 04:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReassignmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_type', models.CharField(choices=[('complaint', 'Complaint'), ('appointment', 'Appointment')], max_length=20)),
                ('ticket_id', models.IntegerField()),
                ('previous_status', models.CharField(max_length=50)),
                ('new_status', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True, default='')),
                ('reassigned_at', models.DateTimeField(auto_now_add=True)),
                ('reassigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reassignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reassigned_at'],
            },
        ),
    ]
