# Generated by Django 6.0.5 on 2026-06-27 06:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workbench', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_type', models.CharField(max_length=20)),
                ('ticket_id', models.IntegerField()),
                ('message', models.TextField()),
                ('status_at_dispatch', models.CharField(max_length=20)),
                ('dispatched_at', models.DateTimeField(auto_now_add=True)),
                ('recipient_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-dispatched_at'],
            },
        ),
    ]
