# Generated by Django 6.0.5 on 2026-06-29 05:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('feedback', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feedback',
            unique_together={('content_type', 'target_object_id', 'submitted_by')},
        ),
    ]
