# Generated by Django 6.0.5 on 2026-06-22 08:06

import grievances.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievances', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='media_path',
            field=models.FileField(blank=True, null=True, upload_to=grievances.models.complaint_media_path),
        ),
    ]
