# Generated by Django 6.0.5 on 2026-07-04 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievances', '0002_alter_complaint_media_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='complaint_subject',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='complaint',
            name='main_category',
            field=models.CharField(choices=[('government', 'Government Services'), ('personal', 'Personal Issues'), ('other', 'Other')], default='government', max_length=20),
        ),
        migrations.AddField(
            model_name='complaint',
            name='sub_category',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
