# Generated by Django 6.0.5 on 2026-07-04 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grievances', '0003_complaint_complaint_subject_complaint_main_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='category',
        ),
    ]
