# Generated by Django 6.0.5 on 2026-07-21 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='identity_document',
            field=models.FileField(blank=True, null=True, upload_to='identity_documents/'),
        ),
        migrations.AddField(
            model_name='user',
            name='supervisor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'sarpanch'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('citizen', 'Citizen'), ('staff', 'Staff / Officer'), ('sarpanch', 'Sarpanch / Nagarsevak')], default='citizen', max_length=10),
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lgd_code', models.CharField(blank=True, default='', max_length=20)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='accounts.state')),
            ],
        ),
        migrations.CreateModel(
            name='Taluka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lgd_code', models.CharField(blank=True, default='', max_length=20)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talukas', to='accounts.district')),
            ],
        ),
        migrations.CreateModel(
            name='VillageCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('lgd_code', models.CharField(blank=True, default='', max_length=20)),
                ('taluka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='villages_cities', to='accounts.taluka')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='village_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residents', to='accounts.villagecity'),
        ),
    ]
