# Generated by Django 6.0.5 on 2026-06-25 03:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('birth_certificate', 'Birth Certificate'), ('death_certificate', 'Death Certificate'), ('income_certificate', 'Income Certificate'), ('residence_certificate', 'Residence Certificate'), ('caste_certificate', 'Caste Certificate'), ('property_certificate', 'Property Certificate')], max_length=50)),
                ('token_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('scheduled_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('form_data_jsonb', models.JSONField(blank=True, default=dict, help_text='Dynamic certificate form fields stored as JSONB')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-scheduled_time'],
            },
        ),
    ]
